# Prepare the application here 
# - Pass a flag that will determine if the python scripts (for data) will run
#   - If flag is TRUE run the python scripts and when the data are ready start nginx
#   - If flag is FALSE just start nginx (data are ready from a previous run)
#   - Set default value of the flag to FALSE
# - Remove requirements.txt (the app will be prepared in a Docker container)